### ISSUE TITLE
Fix beforeEach test

### ISSUE THREAD

**Issue by tumile** [denolib/deno-redis#119]
The way `beforeEach` functions are executed now is not sufficient. 
https://github.com/denolib/deno-redis/blob/96b27457004cbcdb1032066bd70d9527d352873e/tests/test_util.ts#L37-L40
The promise resulted from `f()` is not waited in 
https://github.com/denolib/deno-redis/blob/96b27457004cbcdb1032066bd70d9527d352873e/tests/test_util.ts#L44
so putting client call in `beforeEach` results in error because client has been closed by `afterAll`.

Reproduce
```ts
const suite = new TestSuite("command");

const server = await startRedis({ port: 6500 });
const opts = { hostname: "127.0.0.1", port: 6500 };
const client = await newClient(opts);

suite.beforeEach(async () => {
  await client.flushdb();
});

suite.afterAll(() => {
  stopRedis(server);
  client.close();
});

suite.test("set", async () => {
  assertEquals(await client.set("key", "foo"), "OK");
});

suite.test("keys", async () => {
  await client.set("key1", "foo");
  await client.set("key2", "bar");
  const v = await client.keys("key*");
  console.log(await client.get("key"));
  assertEquals(v.sort(), ["key1", "key2"]);
});

await suite.runTests();

// 
deno test -A tests/command_test.ts
foo
running 2 tests
test [command] set ... error: Uncaught BadResource: Bad resource ID 
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:46:18)
    at async Object.writeAll ($deno$/buffer.ts:204:17)
    at async BufWriter.flush (bufio.ts:467:7)
    at async sendCommand (io.ts:63:3)
```

**Comment by tumile** [comment]
So I tried fixing this 

```ts
runTests = async (): Promise<void> => {
    const promises: Promise<void>[] = [];
    this.tests.forEach((test) => {
      // wait for both beforeEachs and test.func
      const promise = Promise.all(this.beforeEachs.map((f) => f())).then(() =>
        test.func()
      );
      promises.push(promise);
      Deno.test(`[${this.prefix}] ${test.name}`, () => {
        return promise;
      });
    });
    try {
      await Promise.allSettled(promises);
    } finally {
      this.afterAlls.forEach(async (f) => await f());
    }
  };
```

But the order of execution is not as expected
```
OK
OK
running 2 tests
test [command] set ... ok (2ms)
test [command] keys ... FAILED (0ms)
```

The "OK" is from `client.flushdb`. They are executed before all tests are run. pinging @uki00a for thoughts on how to resolve this 😅. Thanks in advance!

**Comment by uki00a** [comment]
How about the following?

```diff
 runTests = async (): Promise<void> => {
     const promises: Promise<void>[] = [];
     this.tests.forEach((test) => {
-      // wait for both beforeEachs and test.func
-      const promise = Promise.all(this.beforeEachs.map((f) => f())).then(() =>
-        test.func()
-      );
-      promises.push(promise);
       Deno.test(`[${this.prefix}] ${test.name}`, () => {
+        // wait for both beforeEachs and test.func
+        const promise = this.beforeEachs.reduce(async (p, f) => {
+          await p;
+          return f();
+        }, Promise.resolve()).then(() => test.func());
+        promises.push(promise);
         return promise;
       });
     });
```

**Comment by tumile** [comment]
I still got BadResource, which means client is closed before the `beforeEach` promise resolves

**Comment by tumile** [comment]
Actually by putting the `promises.push()` inside Deno.test, it's run asynchronously and so if you log `promises` after `tests.forEach` it's empty

**Comment by uki00a** [comment]
```typescript
runTests = async (): Promise<void> => {
    const promises: Promise<void>[] = [];

    const defineTest = (test: { name: string, func: TestFunc }) => {
      const promise = deferred<void>();
      promises.push(promise);
      Deno.test(`[${this.prefix}] ${test.name}`, async () => {
        try {
          // wait for both beforeEachs and test.func
          await this.beforeEachs.reduce(async (p, f) => {
            await p;
            return f();
          }, Promise.resolve()).then(() => test.func());
          promise.resolve();
        } catch (e) {
          promise.reject(e);
        }
        return promise;
      });
    };

    this.tests.forEach(defineTest);
    try {
      await Promise.allSettled(promises);
    } finally {
      this.afterAlls.forEach(async (f) => await f());
    }
  };
```

**Comment by tumile** [comment]
The above didn't work either...
So after a few hours this is what I came up with, a little hacky but works. This ensures that beforeEach and tests are run sequentially.
```ts
  runTests = async (): Promise<void> => {
    try {
      for (const test of this.tests) {
        let res: void | Error;
        try {
          res = await this.beforeEachs
            .reduce((p, f) => p.then(f), Promise.resolve())
            .then(test.func);
        } catch (err) {
          res = err;
        }
        Deno.test(`[${this.prefix}] ${test.name}`, () => {
          if (res instanceof Error) {
            throw res;
          }
        });
      }
    } finally {
      this.afterAlls.forEach(async (f) => await f());
    }
  };
```
