### ISSUE TITLE
Info needed: BadResource: Bad resource ID 

### ISSUE THREAD

**Issue by reselbob** [denolib/deno-redis#89]
Hi:

I run this code and it does indeed consume and report published messages.

```
      (async function () {
        try{
          for await (const { channel, message } of sub.receive()) {
            handler(message);
          }
        }catch(err){
          console.log(err);
        }
```

But, I get an error  `BadResource: Bad resource ID`.

Any idea what this means. I will very much appreciate the help.

Thanks in advance.

**Comment by ebebbington** [comment]
@keroxp I hope you don't mind me giving input...

@reselbob Can you provide the **exact** code you used? How you are running/using it? I assume the above is pseudo-code as well as it isn't valid code. 

Usually I see `Bad Resource ID` when a subprocess using `Deno.run` isn't closed properly or passed invalid values

**Comment by reselbob** [comment]
Here is the code: https://github.com/reselbob/denodemo/blob/master/pubbersubber/types/providers/redis.ts

Here is the project it runs within: https://github.com/reselbob/denodemo/tree/master/pubbersubber

Here is the test: https://github.com/reselbob/denodemo/blob/master/pubbersubber/tests/connection_test.ts , starting at line 63:

You need to have rabbitmq and redis running. I've put this all in the test script found here:

https://github.com/reselbob/denodemo/blob/master/pubbersubber/tests/run_tests

Thanks for your attention. Any help will be appreciated a lot! If the error is due some bad programming on my part, which it very well might be, please forgive me.

**Comment by ebebbington** [comment]
@reselbob Doesn't seem like any of those links work?

**Comment by reselbob** [comment]
Sorry, the repo was private. Now it's not.

**Comment by ebebbington** [comment]
No problem! Do you have the error stack it displays too?

**Comment by reselbob** [comment]
```
error: Uncaught BadResource: Bad resource ID 
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async BufReader._fill (https://deno.land/std@v0.51.0/io/bufio.ts:85:18)
    at async BufReader.readByte (https://deno.land/std@v0.51.0/io/bufio.ts:198:7)
    at async readLine (https://raw.githubusercontent.com/keroxp/deno-redis/master/io.ts:91:15)
    at async readArrayReply (https://raw.githubusercontent.com/keroxp/deno-redis/master/io.ts:141:16)
    at async RedisSubscriptionImpl.receive (https://raw.githubusercontent.com/keroxp/deno-redis/master/pubsub.ts:64:20)
    at async file:///Users/reselbob/Documents/source-tree/denodemo/pubbersubber/types/providers/redis.ts:70:46
```

**Comment by uki00a** [comment]
@reselbob @ebebbington 
Thanks for reporting this issue!
I was able to reproduce the same error.
I'll look into it.

**Comment by uki00a** [comment]
## Steps to reproduce

I have a file named `mod.ts`:

```typescript
import { connect } from "https://deno.land/x/redis@v0.10.2/redis.ts";

const redis = await connect({ hostname: "localhost" });
const sub = await redis.subscribe("test");

(async () => {
  for await (const { channel, message } of sub.receive()) {
    console.log("channel: " + channel);
    console.log("message: " + message);
  }
})();

redis.close();
```

When running the `mod.ts`, the following error occurs:

```
$ deno run --allow-net ./mod.ts
error: Uncaught BadResource: Bad resource ID 
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async BufReader._fill (https://deno.land/std@v0.56.0/io/bufio.ts:85:18)
    at async BufReader.readByte (https://deno.land/std@v0.56.0/io/bufio.ts:198:7)
    at async readLine (https://deno.land/x/redis@v0.10.2/io.ts:91:15)
    at async readArrayReply (https://deno.land/x/redis@v0.10.2/io.ts:141:16)
    at async RedisSubscriptionImpl.receive (https://deno.land/x/redis@v0.10.2/pubsub.ts:64:20)
    at async file:///home/uki00a/projects/deno-redis/sample.ts:8:38
```

**Comment by uki00a** [comment]
@reselbob Hi! This problem has been fixed at [v0.10.3](https://github.com/denolib/deno-redis/releases/tag/v0.10.3). Please update to it.

@ebebbington Thanks for your help! It really helps us.

**Comment by ebebbington** [comment]
@uki00a Shame I didn't have the time to help out more!

**Comment by reselbob** [comment]
I am happy I was able to help. Deno is important as is being able to use Redis with it! Thanks for your attention.
